"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "even-more-fish-plugin/src/main/resources/locales/messages_en.yml",
    "translation": "even-more-fish-plugin/src/main/resources/locales/messages_%two_letters_code%.yml"
  }
]