blank_issues_enabled: false
contact_links:
  - name: EvenMoreFish Discord Server
    url: https://discord.gg/9fRbqWTnHS
    about: Check out additional support on our community discord.
  - name: EvenMoreFish Wiki
    url: https://evenmorefish.github.io/EvenMoreFish/
    about: Check out our official documentation.
